### ISSUE TITLE
use shorthand properties

### ISSUE THREAD

**Issue by yukulele** [two-beards/flexbox-playground#28]
Playground could use shorthand properties like:
* [flex-flow](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow)
* [place-content](https://developer.mozilla.org/en-US/docs/Web/CSS/place-content)
* [place-items](https://developer.mozilla.org/en-US/docs/Web/CSS/place-items)
* [place-self](https://developer.mozilla.org/en-US/docs/Web/CSS/place-self)
* [flex](https://developer.mozilla.org/fr/docs/Web/CSS/flex)

Example:
```css
.container {
	display: flex;
	flex-direction: column;
	flex-wrap: wrap;
	justify-content: center;
	align-content: center;
}
```
could be shortened to:
```css
.container {
	display: flex;
	flex-flow: column wrap;
	place-content: center;
}
```
